### ISSUE TITLE
Create an onboarding script readme

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/workshop-devcon4#5]
The onboarding script does not have a readme. For the start the Readme could be very basic.

It should be done in the eth_cape_town branch: https://github.com/raiden-network/workshop/tree/eth_cape_town/tools/onboarder

Create the Readme including https://github.com/raiden-network/workshop/tree/eth_cape_town#on-boarding

**Comment by agatsoh** [comment]
Hi @christianbrb the onboarder script instructions have already been written here https://github.com/raiden-network/workshop/tree/eth_cape_town#on-boarding. But if you want to write a little something just for the context then we could write something there.
